### PR TITLE
Refactor employee role manager

### PR DESCRIPTION
**Pull request by KAYEMBAJONATHAN**
- Add Refactor Employee Role Manage Controller
- Add updates unit tests  for this controller
Screenshot 2024-07-11 105006

### CODE REVIEW

**Review by MathildaShongwe15 — COMMENTED** [review]
Why is coverage not at 100%?

**Comment by KAYEMBAJONATHAN** [comment]
> Why is coverage not at 100%?

@MathildaShongwe15   I spoke with Eduan and he did allow me to leave it for now

**Comment by bseptember** [comment]
@KAYEMBAJONATHAN well done!

**Review by bseptember — APPROVED** [review]

**Review by MathildaShongwe15 — APPROVED** [review]

**Review by ReitumetseMoloto — APPROVED** [review]

**Review by EduanO — CHANGES_REQUESTED** [review]
Looks good, Just require code to be in a service. Not allowed to have business logic in controller

**Comment by bseptember** [comment]
> Looks good, Just require code to be in a service. Not allowed to have business logic in controller

@KAYEMBAJONATHAN @EduanO with regards to this, if the services are not yet refactored, should the checks for said services be removed?

**Review by EduanO — APPROVED** [review]

**Pull request merged**
