### PR TITLE
DEV | Backend bug fixes

### PR DESCRIPTION
**Pull request by bseptember**
### OVERVIEW

[ticket](https://dev.azure.com/retro-rabbit/HRIS/_sprints/taskboard/HRIS%20Team/HRIS/Sprint%2027?workitem=10398)

**Fixes added:**

1. An issue was that the identity class did not cater for inactive users or users with no role. A newly created user has an assigned role in the database, they need to login using their email then auth0 role is assigned via this. However the identity class checks the role and finds the auth0 role is empty and then throws an exception. This was not correct.

3. The CheckDuplicateIdNumber should be different when calling the update vs create new employee. Another issue regarding this was the FromQuery did not pull in the correct parameters since the variable name was not correct so it did not match the url.
 
5. Added permission for the employee role so that the user is allowed to view and update their own certificates.
6. Added permission for the employee role so that the user is allowed to get their field codes for the accordions.
7. Added permission for the employee role so that the user is allowed to view and update their own banking details.
 
9. Fixed/updated unit tests concerned.

### CODE REVIEW

**Comment by ReinoRabbit** [comment]
Please add the coverage report for the unit tests

**Review by madwizzard — APPROVED** [review]

**Review by madwizzard — CHANGES_REQUESTED** [review]
The graphs dont load because the endpoint is being called with empId -1


image


Address get returns 500 not sure why.
Also Post and put return 500

**Comment by bseptember** [comment]
> Please add the coverage report for the unit tests
@ReinoRabbit 
**PropertyAccessController:**
image

**BankingAndStarterKitService:**
image

**EmployeeCertificationService**
image

**EmployeeService**
image

**FieldCodeOptionsService**
image

**EmployeeController**
image

**Comment by bseptember** [comment]
> The graphs dont load because the endpoint is being called with empId -1
> 
> image
> 
> Address get returns 500 not sure why. Also Post and put return 500

@EstiaanBritz not on my end?
image

**Review by ReinoRabbit — APPROVED** [review]

**Review by madwizzard — APPROVED** [review]

**Review by Wimmas — APPROVED** [review]

**Pull request merged**
