### PR TITLE
Joe/refactor property dto

### PR DESCRIPTION
**Pull request by KAYEMBAJONATHAN**
1. Add remove the constructor from propertyDto 
2. Add also refactor the new propertyDto
image

### CODE REVIEW

**Comment by tbddorothy** [comment]
Please check your source and target branches

**Comment by KAYEMBAJONATHAN** [comment]
> Please check your source and target branches, your target should be develop and your source should be your branch

@tbddorothy  fixed

**Comment by tbddorothy** [comment]
Please add screenshots of the coverage report

**Comment by KAYEMBAJONATHAN** [comment]
@tbddorothy 
dto

**Review by tbddorothy — APPROVED** [review]

**Review by AWallsRR — APPROVED** [review]

**Review by MTSchoeman — APPROVED** [review]

**Pull request merged**
